/*
Skeleton Profile Options 
SKEL_PROFILE_ALL	 
SKEL_PROFILE_UPPER 
SKEL_PROFILE_LOWER 
SKEL_PROFILE_HEAD_HANDS

Skeleton Joint Names
SKEL_HEAD 
SKEL_NECK 
SKEL_TORSO
SKEL_WAIST 
SKEL_LEFT_COLLAR 
SKEL_LEFT_SHOULDER 
SKEL_LEFT_ELBOW 
SKEL_LEFT_WRIST 
SKEL_LEFT_HAND 
SKEL_LEFT_FINGERTIP 
SKEL_RIGHT_COLLAR 
SKEL_RIGHT_SHOULDER 
SKEL_RIGHT_ELBOW 
SKEL_RIGHT_WRIST 
SKEL_RIGHT_HAND	 
SKEL_RIGHT_FINGERTIPP 
SKEL_LEFT_HIP 
SKEL_LEFT_KNEE 
SKEL_LEFT_ANKLE 
SKEL_LEFT_FOOT 
SKEL_RIGHT_HIP 
SKEL_RIGHT_KNEE 
SKEL_RIGHT_ANKLE 
SKEL_RIGHT_FOOT
*/



